// AUTO-GENERATED by scripts/sync-overrides.mjs. Do not edit by hand.
// Source: https://docs.google.com/spreadsheets/d/1UW3CLv5HQUVMdl-HjI1qzeNfrAmmZLlnE3isN-zo2Ak
// Regenerate with: npm run sync-overrides

export type VinylOverride = {
  imageUrl: string;
  // "photo" = use as the vinyl image (cropped & circle-masked normally).
  // "svg"   = don't show a photo; sample the image's outer color and render
  //          the SVG fallback in that color.
  kind: "photo" | "svg";
  // Free-form note from the sheet (e.g. "Outer green color"). Informational.
  note: string | null;
};

const OVERRIDES: Readonly<Record<number, VinylOverride>> = {
  14013189: { imageUrl: "https://i.discogs.com/-OnGdM-L8y2qwu1GTZJF_4oLNbDLYhArrWZw_pFQIIk/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0MDEz/MTg5LTE2MTU3NjI0/NjktMTc3OS5qcGVn.jpeg", kind: "svg", note: "Outer green color" },
  14826236: { imageUrl: "https://i.discogs.com/Q5t-pRwy1sYlUisC3Noa-vg8xJC6tvf4Dx_7AskqnqI/rs:fit/g:sm/q:90/h:599/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE0ODI2/MjM2LTE1ODIzNTE4/NDYtMTk2MC5qcGVn.jpeg", kind: "photo", note: null },
  15136695: { imageUrl: "https://i.discogs.com/KN9PALMxUcdjw6eWUhBHVZPBWCLt38o5LduAxJALTmQ/rs:fit/g:sm/q:90/h:586/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1MTM2/Njk1LTE1ODkyMzgy/OTEtOTYwNy5qcGVn.jpeg", kind: "photo", note: null },
  15392788: { imageUrl: "https://i.discogs.com/aUN0pHpfS3vgRe-WjtIswkfMJ-_Kq0d5PJM1CfrZgok/rs:fit/g:sm/q:90/h:600/w:590/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1Mzky/Nzg4LTE2MDAwNTAz/MDktMzg5Mi5qcGVn.jpeg", kind: "photo", note: null },
  15513317: { imageUrl: "https://i.discogs.com/-Jw2L0iQYblugSukvmO2zlt7Az9Hp8ftrdKmM9mmpzg/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1NTEz/MzE3LTE2NTcyMzkw/NzYtNDIxNS5qcGVn.jpeg", kind: "photo", note: null },
  15877561: { imageUrl: "https://i.discogs.com/ZVYtj7YRvLGTVfnWpXEjw0py4ovyFiBCLIIO9JvoWYQ/rs:fit/g:sm/q:90/h:594/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE1ODc3/NTYxLTE3Nzc5Mjg1/MDctNDM4NC5qcGVn.jpeg", kind: "photo", note: null },
  19528042: { imageUrl: "https://i.discogs.com/jualZ9OxbuWs0H-nx_Gkz0wZmUlfxWSLlf76T3K9xj4/rs:fit/g:sm/q:90/h:600/w:597/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5NTI4/MDQyLTE2NDIyNjkz/MjktOTM1MS5qcGVn.jpeg", kind: "photo", note: null },
  19612117: { imageUrl: "https://i.discogs.com/_ayU7gDAtquomCNQ4h9jQ9ZnhSxhjL-_JqJ3JzTqPEU/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE5NjEy/MTE3LTE2NDgzNDUy/ODgtNTgyNS5qcGVn.jpeg", kind: "photo", note: null },
  20087017: { imageUrl: "https://i.discogs.com/YRkLukvsrDK5FoSEK-AMZYt7uGemW0PY2SuaeDuwJm8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIwMDg3/MDE3LTE2MzA3OTMw/OTktODQ2Mi5qcGVn.jpeg", kind: "photo", note: null },
  21687553: { imageUrl: "https://i.discogs.com/uPLr0FbT1rWLznV81xeyz5RELn9p9gjoWSVaBeiZBXg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxNjg3/NTUzLTE2OTk3MzY0/NTktMjM5MC5qcGVn.jpeg", kind: "photo", note: null },
  21928996: { imageUrl: "https://i.discogs.com/9tzJ1F-pqdoRs-MBImGj48Q6UT0E4YSv7_0HqevFTYU/rs:fit/g:sm/q:90/h:600/w:400/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIxOTI4/OTk2LTE2NDQ5NjQ1/OTYtMTA3MC5qcGVn.jpeg", kind: "svg", note: "Use pink to create custom SVG version" },
  22161283: { imageUrl: "https://i.discogs.com/nhurbrspuylIOsRBh7t1egg5N_kvEvX08nW1NHzRiU0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyMTYx/MjgzLTE2NDQ5ODM0/MTQtNjIwMy5qcGVn.jpeg", kind: "svg", note: "Outer silver color" },
  23193389: { imageUrl: "https://i.discogs.com/Oxjth8NF0F88pybJ-uTTv0S7yBoaTvX2c0xHTHxcFUg/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzMTkz/Mzg5LTE2NTIzOTI4/MTQtNzMwMy5qcGVn.jpeg", kind: "photo", note: null },
  23412182: { imageUrl: "https://i.discogs.com/OWV07x19Qh-5NjIMMtNCvOns8SVrvGOeR9j238p4IO8/rs:fit/g:sm/q:90/h:600/w:576/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzNDEy/MTgyLTE2NTM5NDAw/NTQtMTQyOC5qcGVn.jpeg", kind: "photo", note: null },
  23643326: { imageUrl: "https://i.discogs.com/rUaPjZPFnb_nsMczztisdgzDmSFKzo1TkCp4whRvez8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzNjQz/MzI2LTE2OTc5MzU0/OTAtNTM4OS5qcGVn.jpeg", kind: "photo", note: null },
  23854310: { imageUrl: "https://i.discogs.com/_WJw6ZWqkFMaO3nTwZTKLMIGHqEAaG37x5c2SAS-eZs/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzODU0/MzEwLTE2NTg0NzM4/MjUtNzUxOC5qcGVn.jpeg", kind: "photo", note: null },
  24082382: { imageUrl: "https://i.discogs.com/nFvjKuCyZYFf5QjzoX0spfBU-oCpVbXEesxZJVTn4_s/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0MDgy/MzgyLTE2NTk0ODE5/NjAtMTA5MC5qcGVn.jpeg", kind: "photo", note: null },
  24608459: { imageUrl: "https://i.discogs.com/qKIGFmr1Otze1Si6CY2EBNM-LEhzY1mnXuRfELv5wCM/rs:fit/g:sm/q:90/h:600/w:450/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI0NjA4/NDU5LTE2NjM5NzQ2/NzgtODEwMS5qcGVn.jpeg", kind: "svg", note: "Outer clear color" },
  25045969: { imageUrl: "https://i.discogs.com/H_IHiJuWEcwnClBCoRo5dDPupYs1xAqycDE6W66_LfI/rs:fit/g:sm/q:90/h:600/w:400/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1MDQ1/OTY5LTE2Njc2OTc3/NzEtNzg5NS5qcGVn.jpeg", kind: "svg", note: "Use creamy white to create custom SVG version" },
  25247080: { imageUrl: "https://i.discogs.com/Ty0IQJEWxIlCcrSYeeZUnpDwySXbQOD-iJLOe428UIw/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1MjQ3/MDgwLTE2NjkxMjc4/MzktNzY5Mi5qcGVn.jpeg", kind: "photo", note: null },
  25558660: { imageUrl: "https://i.discogs.com/0jom6-vDNDa3Cwj5bJcVazSs_qaEVVh3qIkRHbKg2BQ/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI1NTU4/NjYwLTE3MDUxOTg3/ODEtNDE1MC5qcGVn.jpeg", kind: "photo", note: null },
  26205794: { imageUrl: "https://i.discogs.com/ZxI_Byy0zdJKypFBgRNASQlHHidY_UKJ3Jf5RFmwcUg/rs:fit/g:sm/q:90/h:600/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MjA1/Nzk0LTE2ODU3ODM5/NTMtMzMxNC5qcGVn.jpeg", kind: "photo", note: null },
  26226236: { imageUrl: "https://i.discogs.com/KIo15rCgXzAcLBnx2ZPnfO1iU35mP-qjP99Uk8OpiLI/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2MjI2/MjM2LTE2NzczOTk3/MTItNDU1NC5qcGVn.jpeg", kind: "svg", note: "Outer blue color" },
  26601599: { imageUrl: "https://i.discogs.com/x3MrzT6zp3FzRsBbyUzUmSgWRJm29XRA5QXRtQ6XG7Y/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2NjAx/NTk5LTE2ODAyNTgw/MTQtNzY0NC5qcGVn.jpeg", kind: "photo", note: null },
  26805638: { imageUrl: "https://i.discogs.com/12kbqdAnAt8gVapwtd8qCM6e0JWRf5t2G5fHF5bHiVw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2ODA1/NjM4LTE2ODIyMDQw/MTYtMzUxMi5qcGVn.jpeg", kind: "photo", note: null },
  26815136: { imageUrl: "https://i.discogs.com/3GqaC0BXt9CV0AmwQ5RLffrYcMNEmfxrHu9iDidP0jI/rs:fit/g:sm/q:90/h:597/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2ODE1/MTM2LTE2OTExNTAw/NTEtNzkyMy5qcGVn.jpeg", kind: "svg", note: "Outer green color" },
  26847797: { imageUrl: "https://i.discogs.com/9BRUHuKWQsVDfYEdFa5tsu5PBCD9QYFDRVQfRUizMq8/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI2ODQ3/Nzk3LTE2ODIzMDQ1/NDctMzMxOC5qcGVn.jpeg", kind: "svg", note: "Outer silver color" },
  27115944: { imageUrl: "https://i.discogs.com/5twC7ETP4IF_Q2dul3WhXpbCo1RTJ8PJOSsRvp1XBjU/rs:fit/g:sm/q:90/h:386/w:503/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3MTE1/OTQ0LTE2ODQ0MTMy/NTYtNzU3Ny5wbmc.jpeg", kind: "photo", note: null },
  27363366: { imageUrl: "https://i.discogs.com/hZED4ObAGnFhWKyg_DGZqxHTBrvQaKzOjtrRxdYwQsA/rs:fit/g:sm/q:90/h:598/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3MzYz/MzY2LTE2ODgxNjMz/NzUtODgxNS5qcGVn.jpeg", kind: "photo", note: null },
  27485277: { imageUrl: "https://i.discogs.com/TCGC10yNUJXa2uHeIxgZR7A-FVDTqsef5FTD6VNbKY4/rs:fit/g:sm/q:90/h:600/w:578/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NDg1/Mjc3LTE2ODc4MjUy/ODUtMjQ4Mi5qcGVn.jpeg", kind: "photo", note: null },
  27528699: { imageUrl: "https://i.discogs.com/jLdw7EJ36tKlaLPf8MHQ00Mp17YzZ6P1ofy1Nm7ZNk0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NTI4/Njk5LTE2ODgxMjQx/NzEtMjE5MC5qcGVn.jpeg", kind: "photo", note: null },
  27598578: { imageUrl: "https://i.discogs.com/ZuMH1PUhLWMitNuPze-zPQhNPBfxFOVZnyWpKCMbtWE/rs:fit/g:sm/q:90/h:600/w:594/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NTk4/NTc4LTE2ODkxOTI5/MzMtMzU3Ni5qcGVn.jpeg", kind: "photo", note: null },
  27613062: { imageUrl: "https://i.discogs.com/AKZdZgjZYjSs50wmYhnZeT30DKiBbk9dvoqEkHHexsQ/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NjEz/MDYyLTE2OTEzODEy/ODktNTg3Ni5qcGVn.jpeg", kind: "photo", note: null },
  27636876: { imageUrl: "https://i.discogs.com/JAdyDYtl_qm_SuLSkQRyCefru12KQrBaW92lKTeZB9g/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3NjM2/ODc2LTE2ODkwMzAx/MjEtOTI3Mi5qcGVn.jpeg", kind: "photo", note: null },
  27897450: { imageUrl: "https://i.discogs.com/kOGB-lzxqT7wptPrV2ijFNB8URT8I7y3FQdi9s5W1gU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI3ODk3/NDUwLTE2OTgzNzA5/MTgtMjYyMy5qcGVn.jpeg", kind: "photo", note: null },
  28085920: { imageUrl: "https://i.discogs.com/9D9cPiv2dQospm_wPxdI510Q1B-PU621IRObbFgZoqo/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4MDg1/OTIwLTE2OTMwNzg0/MDMtODQyMC5qcGVn.jpeg", kind: "photo", note: null },
  28142536: { imageUrl: "https://i.discogs.com/gUuZjsELSSKJr9TCdgthNVQDt6348OB5rhXungN5ocM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4MTQy/NTM2LTE3Nzc4Mzkx/NDUtMjM0My5qcGVn.jpeg", kind: "photo", note: null },
  28267735: { imageUrl: "https://i.discogs.com/TpnLo2e0eVCtiKpi5kdYGpq2zq7j1Dl8JbRObz0wUrk/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4MjY3/NzM1LTE2OTQ3ODQ4/NDYtODcwNi5qcGVn.jpeg", kind: "photo", note: null },
  28366834: { imageUrl: "https://i.discogs.com/qoLUfiEI3TAhWmosA_-DVVb3jopMcEYtEVDApDLrW-4/rs:fit/g:sm/q:90/h:589/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4MzY2/ODM0LTE2OTU1ODk5/MzktNTg0My5qcGVn.jpeg", kind: "photo", note: null },
  28459957: { imageUrl: "https://i.discogs.com/PY0R_7QtFf9REjatYzpcxF5Iw8V7MIgbQbW98oi1qqM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4NDU5/OTU3LTE2OTYyMDIw/MDAtOTQ5OS5qcGVn.jpeg", kind: "photo", note: null },
  28848508: { imageUrl: "https://i.discogs.com/aa_Lx5uZpDlyJJNkwrLbcdysy1HVsq_S_iEg1yrZ70c/rs:fit/g:sm/q:90/h:600/w:585/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI4ODQ4/NTA4LTE2OTk3NDg3/NjItMjI5Ni5qcGVn.jpeg", kind: "photo", note: null },
  29358322: { imageUrl: "https://i.discogs.com/tzEaVAoBlfcCwAHxnLghGCRCOqIa5ICUob_UnMZc_Qc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MzU4/MzIyLTE3MTIyNzk3/MzEtNTk1MC5qcGVn.jpeg", kind: "svg", note: "Outer blue color" },
  29358724: { imageUrl: "https://i.discogs.com/4bQii66uH4pNTajfC8MqW1ovbtdVjgHnUgwGq1AsnbY/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5MzU4/NzI0LTE3NTcyNjI3/MzUtNzkxNC5qcGVn.jpeg", kind: "photo", note: null },
  29522527: { imageUrl: "https://i.discogs.com/xFx3GCkvksnfCcf4FNxbyoGYmsOHOfVWjUH1OXN1xmg/rs:fit/g:sm/q:90/h:600/w:588/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5NTIy/NTI3LTE3MDU1NjQy/MzAtMzEzMy5qcGVn.jpeg", kind: "photo", note: null },
  29864632: { imageUrl: "https://i.discogs.com/FV2LXYZNKcymdRIfprNIdaDluWFdFBzBDvpXl2JFez4/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTI5ODY0/NjMyLTE3MTgzNjI4/MDMtODcwMS5qcGVn.jpeg", kind: "photo", note: null },
  30423341: { imageUrl: "https://i.discogs.com/J2wUFtrLlDYF8pbx7r8jpjyFCoIt9ho6UH9bpteieMA/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwNDIz/MzQxLTE3MTM3ODMy/MjUtODA0NC5qcGVn.jpeg", kind: "photo", note: null },
  30447449: { imageUrl: "https://i.discogs.com/-VIfAb3LkydWdcXNSFKuwxV0kGgesJdXhqsynGcSgSg/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwNDQ3/NDQ5LTE3MTM1NzM0/OTQtMjk2MC5qcGVn.jpeg", kind: "photo", note: null },
  32037092: { imageUrl: "https://i.discogs.com/V9528IqI1TwoN7P6kbZQv3F_fR_Vi-1R_qxmwbz0eIE/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMDM3/MDkyLTE3MzAzMDc5/MTItMzkzMi5qcGVn.jpeg", kind: "photo", note: null },
  32165484: { imageUrl: "https://i.discogs.com/IE44GMgqtKk7bUsujf2Qh8dTLeXdFXIK7kY0X8dpxvo/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMTY1/NDg0LTE3MzA0OTEw/MjgtMjc5OC5qcGVn.jpeg", kind: "photo", note: null },
  32240436: { imageUrl: "https://i.discogs.com/mFsWUh8S4WVoMeNTGbkls27dDXplrSfbMlGHgN82ILc/rs:fit/g:sm/q:90/h:600/w:594/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMjQw/NDM2LTE3MzExNTk3/NjItODI3MS5qcGVn.jpeg", kind: "photo", note: null },
  32266428: { imageUrl: "https://i.discogs.com/4ExCoYolMyfKcQoQcEOxITB27ydssUM1Q1PnPy-IFrc/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMjY2/NDI4LTE3MzEzODU5/NDYtODg4Mi5qcGVn.jpeg", kind: "photo", note: null },
  32431017: { imageUrl: "https://i.discogs.com/GeIbzb05hDjHCfjb7PMrarPbs5XgEDnctLAEd9uUFmk/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNDMx/MDE3LTE3MzI5MDEy/NDItNjEzMy5wbmc.jpeg", kind: "photo", note: null },
  32435361: { imageUrl: "https://i.discogs.com/NbXWW0Pp5NJY8Y05rurDs8_7SiVxN-tGUwzd-Cgumcw/rs:fit/g:sm/q:90/h:555/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNDM1/MzYxLTE3MzMwNzU3/NzItMjAyNi5qcGVn.jpeg", kind: "photo", note: null },
  32582244: { imageUrl: "https://i.discogs.com/6xM6gL598uE7b08Yqk4IUR1CtiAjpijVolSr_A7WkGg/rs:fit/g:sm/q:90/h:566/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNTgy/MjQ0LTE3MzUxMTc2/ODEtNzgwMi5qcGVn.jpeg", kind: "photo", note: null },
  32700024: { imageUrl: "https://i.discogs.com/gSe3M_f7QUCnZ25f2ld7wDFbXOk2CAPes0VLmxWB_EQ/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNzAw/MDI0LTE3MzYwNDMy/ODgtNzA2MC5qcGVn.jpeg", kind: "photo", note: null },
  32751522: { imageUrl: "https://i.discogs.com/11BH4aHxrCs5-K0pi-IF0DY24i39Y0hYgw6QVlWUEQ8/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyNzUx/NTIyLTE3NzM4MzU0/NzQtNjE0Ny5qcGVn.jpeg", kind: "photo", note: null },
  33195051: { imageUrl: "https://i.discogs.com/_3uko2uufjFi2J0Q3fuizRe47zWoh2elEruuup-6cjw/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzMTk1/MDUxLTE3NDAwNjg5/MTUtODQzOS5qcGVn.jpeg", kind: "photo", note: null },
  33650664: { imageUrl: "https://i.discogs.com/jRAxHnj9ZoFG5aUKfdpRgmv30eCmY0N9UU85jN_mAak/rs:fit/g:sm/q:90/h:600/w:593/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNjUw/NjY0LTE3NDQzMTkz/NDUtOTE5Ni5qcGVn.jpeg", kind: "photo", note: null },
  33672588: { imageUrl: "https://i.discogs.com/ljyM-VqBLZYlR5DfpTM6Gyx4o1xqSplruxlEtxGUd4Y/rs:fit/g:sm/q:90/h:600/w:593/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNjcy/NTg4LTE3NDU1MTI0/OTMtMzkxMy5wbmc.jpeg", kind: "photo", note: null },
  33687495: { imageUrl: "https://i.discogs.com/9zacg3nNe_-YoELdbnI1iLNHsxshsJP1xEljVDJOlfo/rs:fit/g:sm/q:90/h:450/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNjg3/NDk1LTE3NDQ1NTYw/NDQtODk0Ni5qcGVn.jpeg", kind: "photo", note: null },
  34398277: { imageUrl: "https://i.discogs.com/T6l9g3tioKeM3tOtcVoHOcTaBq73nv8EUh-HbRaGLxc/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0Mzk4/Mjc3LTE3NTExMzU2/NzktMjQ5OC5qcGVn.jpeg", kind: "photo", note: null },
  34571488: { imageUrl: "https://i.discogs.com/wC6zaE-6ym95rAHM32I79_tZpeg_xaoXRWJExGXkcTs/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0NTcx/NDg4LTE3NTI4MTk4/NDItMTU5NC5qcGVn.jpeg", kind: "photo", note: null },
  34579129: { imageUrl: "https://i.discogs.com/DrhuRQj6OFmMGBZA1NtWbxH9WJkx9e2wtKsJGxz--Jg/rs:fit/g:sm/q:90/h:600/w:449/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0NTc5/MTI5LTE3NTM2OTE4/MjEtOTEyNi5qcGVn.jpeg", kind: "photo", note: null },
  34670020: { imageUrl: "https://i.discogs.com/E7AMnE2pTXivvwzWrV0gcnvtdsg0pXUco5ISwBrPOaw/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM0Njcw/MDIwLTE3NTQzNjcw/MTUtMTU1NC5qcGVn.jpeg", kind: "photo", note: null },
  35716615: { imageUrl: "https://i.discogs.com/TsS4P8aiw1JV0y9-5lU6uBkSqzfQ6IqvV_oIK0wyw30/rs:fit/g:sm/q:90/h:572/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM1NzE2/NjE1LTE3NjM2NjUy/NTctNzUwOC5qcGVn.jpeg", kind: "photo", note: null },
  36957222: { imageUrl: "https://i.discogs.com/kLZDiAUR7n8eZizNp-aLEuVmdQeGAA41_VoG3tsO5xU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM2OTU3/MjIyLTE3NzUyNTM5/MDMtOTM1Ni5qcGVn.jpeg", kind: "photo", note: null },
  37087599: { imageUrl: "https://i.discogs.com/lj3nCAw9eifi3Dn1Sp5x0q4IBRcetBdPAxzZlv-Y6NE/rs:fit/g:sm/q:90/h:600/w:586/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MDg3/NTk5LTE3NzYzODY3/NzktNzI3OC5qcGVn.jpeg", kind: "svg", note: "Use outer white color to create custom SVG version" },
  37104669: { imageUrl: "https://i.discogs.com/ynZm7PvUzM2YReuToM3ORf3AZf6jruotcRxxnKnDDEA/rs:fit/g:sm/q:90/h:600/w:599/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MTA0/NjY5LTE3NzY1Mjg5/MDgtODg3NS5qcGVn.jpeg", kind: "photo", note: null },
  37107153: { imageUrl: "https://i.discogs.com/oTVq08YZB8IbgX_E_WIvso2tMZrAUzcInxmm9nhRI6o/rs:fit/g:sm/q:90/h:591/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTM3MTA3/MTUzLTE3NzY1Mzk1/MjktNzU4NS5qcGVn.jpeg", kind: "photo", note: null },
};

export function getVinylOverride(releaseId: number): VinylOverride | null {
  return OVERRIDES[releaseId] ?? null;
}
